### ISSUE TITLE
win7core can't work.

### ISSUE THREAD

**Issue by leeseed1** [GFW-knocker/Xray-core#17]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

v1.8.21-mahsa-r1

### Description

win7 32/64 core can't work.

### Reproduction Method

win7 32/64 core can't work.

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by GFW-knocker** [comment]
fixed in v1.8.21-mahsa-r2 and above.
